### ISSUE TITLE
Lack image_registration_ file 

### ISSUE THREAD

**Issue by phenix1983** [sthoduka/fmt_motion_detection#1]
can not get the  image_registration_.getBorderMask() source code

**Comment by sthoduka** [comment]
hi @phenix1983 thanks for pointing it out. The submodule link was broken somehow. I've fixed it now.

Please clone with `git clone --recursive https://github.com/sthoduka/fmt_motion_detection.git`

**Comment by phenix1983** [comment]
Firstly, thank you very much for your reply.  I've followed your instructions to compile. 
execute command:  cmake -DCMAKE_BUILD_TYPE=Release ..
 Still Cmake Error:  the following variables are used in this project . but they are set to NOTFOUND, Please set them or make sure they are set and tested correctly in the CMake files: 

FFTW_LIBRARY
        linked by target "imreg_fmt" in directory xxx/fmt_motion_detection/imreg_fmt

--Configuring incomplete. errors occurred!

**Comment by phenix1983** [comment]
Can you share a project can run with Vs2013 on windows?

**Comment by sthoduka** [comment]
I don't have Windows, sorry. If you get it running on Windows, please send a merge request!

**Comment by phenix1983** [comment]
Thank you very much for your reply. I have another question about some parameters configure, for example, if the original image resolution is 1920x1080,  resize to 960x540, well,  any parameters should be changed? such as variable min_area, cluster_euclidean_threshold ,min_magnitude, max_magnitude, difference_area_threshold_ and difference_intensity_threshold_.  If the light get dark. also some parameters should be changed? Thank you.

**Comment by sthoduka** [comment]
I think I made most parameters scale based on the image size. But I will go through them one by one.

[`min_area`](https://github.com/sthoduka/fmt_motion_detection/blob/master/src/motion_detection.cpp#L74): defines the minimum size of the bounding boxes. Currently this is 8 times the number of columns. If you think you are getting too small bounding boxes, you can increase this.

[`cluster_euclidean_threshold`](https://github.com/sthoduka/fmt_motion_detection/blob/master/src/motion_detection.cpp#L8): pixels in the contours which are closer than this threshold are considered to be part of one cluster. Currently a tenth of the number of columns. If you think you are getting too many bounding boxes close to each other and want to combine them, then increase this threshold.

[`min and max_magnitude`](https://github.com/sthoduka/fmt_motion_detection/blob/master/src/motion_detection.cpp#L72): it looks like these are not being used..I can't remember why I was using them :)

[`difference_area_threshold`](https://github.com/sthoduka/fmt_motion_detection/blob/master/src/motion_detection.cpp#L7): this is also not being used. It was supposed to be used in [`getEdgeMask`](https://github.com/sthoduka/fmt_motion_detection/blob/master/src/image_differencing.cpp#L46). The edge mask is only important if your camera is moving. It is there to remove artifacts from imprecise registration.

[`difference_intensity_threshold`](https://github.com/sthoduka/fmt_motion_detection/blob/master/src/motion_detection.cpp#L7): intensities in the difference image below this threshold are set to black in the thresholded image. Currently this is set to 40; i.e. if the intensity of the pixel is below 40, it is set to black, and anything between 40 and 255 are set to white in the thresholded image. This is important for your last point. If your lighting conditions are quite dark, you might need to reduce this threshold.

**Comment by phenix1983** [comment]
Thank you for your patience.

int rect_width = im.rows / 45;  /*45 is a experience value?*/
int rect_height = im.cols / 45;
int min_area = (im.cols * im.rows) / 1920; /*1920 is a experience value or a image width?*/
aspect_ratio > 6.0 || aspect_ratio < 1.0/6.0 /*6.0 is a experience value?*/

**Comment by sthoduka** [comment]
I got those numbers by trial and error mostly (is that what you mean by experience value?). I had one or two videos on which I was testing, and I tuned the values for those videos. They are not image widths/heights. I was working with 320x240 sized images.

**Comment by phenix1983** [comment]
Thank you. "experience  value" is just the same meaning to your trial ：）
My application scene is moving object detection when camera moving, and the camera is installed on car rear.Video image resolution is 1920x1080，I will try to adjust the parameters.

**Comment by phenix1983** [comment]
:) how to use variable difference_area_threshold_?  because the camera is moving,  and I want to know  motion of moving object , the motion is big or small.

**Comment by phenix1983** [comment]
:) how to use variable difference_area_threshold_? because the camera is moving, and I want to know motion of moving object , the motion is big or small. somtimes  the moving object cannot be detected ,such as in the underground parking ,if we could only see the someone's foot moving or legs moving , in this case,  the foot or legs  can not be detected in realtime video.

**Comment by phenix1983** [comment]
just now I found that  Maybe “the step 4. edge and border masking” will filtered the contours of moving foot or moving legs. I can see the moving contour in image "diff_threshold".but can not see in image"difference_masked".

**Comment by phenix1983** [comment]
if set divisor = 2; befor"if (frame_number % divisor !=0) continue;" .the moving object cannot be detected corrrectly;

**Comment by sthoduka** [comment]
difference_area_threshold_ is not used currently. I think earlier I was using it to also check the areas of the bounding boxes of the edge contours. If the area was low, I'd consider it an edge. 

and yea, the problem with edge masking is that it also removes/masks out some of the true positives (moving objects). It is a trade-off between getting too many false positives and too many false negatives. The frames are never perfectly aligned (because we are using just a similarity transform), so the areas in the image where there is a sharp contrast (for example the edge of a wall), the difference image will have a high value. Since these are usually narrow and long areas, we try to find those and mask them out. The border mask is there so we don't consider areas that are in the first image, but are missing from the second image (due to camera movement). My suggestion is to remove the edge mask, and if you see too many false positives, add it back and play with the parameters so they fit your use case.

The divisor is there to skip frames if we want to. For example, if you capture at 30 Hz, there will be very little movement between consecutive frames. So instead we only register every 5th or every 10th frame, so there is enough motion between them. If you have fast motions, just set the process_frame_rate equal to the initial_frame_rate. If you have slow motions, lower the process frame rate (to 15, 10 or 5).

**Comment by phenix1983** [comment]
[2017_1107_164114_054A.zip](https://github.com/sthoduka/fmt_motion_detection/files/1473552/2017_1107_164114_054A.zip)
Would you like to help me to test this sequence? thank you.

**Comment by sthoduka** [comment]
Unfortunately I don't have much time to test too much. 

I took a look at the video. One of the problems is the fish-eye-like distortion. You should try to undistort the image before. The FMT image registration method only performs a similarity transform, so the distortion is problematic and will cause a lot of false positives. That's why the white lines on the floor etc. are not registered properly.

I added an extra argument for resizing. Earlier it was just halving the image size (because I had 640x480 and wanted to use 320x240). 

For your video, I tried the following:
`./fmt_motion_detection_video ../../2017_1107_164114_054A.avi -r 4 -s -fps 6`

(resized to 480x270 and only use every 5th frame).

But you're right, lots of false positives and not all motions are detected.

**Comment by phenix1983** [comment]
：） thank you for your advice, I've added Remap code to undistort the image. I cut ROI area odfthe bottom half of the image 960x540, the ROI size is 960x270 .test again. when fps <30, such as 15, 
the  variable divisor =2, maybe motion is big, the overlap region is small. So if I use other approach to do image registration, such as image registration based on SIFT/ORG, and also get the border mask.In theory, the effect might be better . I'll try it ,thank you again.

**Comment by phenix1983** [comment]
Hi,I'm so grateful to you . I've fixed my problem.：）Thank you for your patience ,again.

**Comment by sthoduka** [comment]
You're welcome :)
Can you describe briefly how you solved your problem? It would be good to know for adding more instructions or improving the method.

**Comment by phenix1983** [comment]
Well. Firstly,take your advice,add code do undistort the image.Then, I didn't change the algorithm code and use the your configure parameters, resized the image to 960x640.(not 480x320)
   ./fmt_motion_detection_video ../../2017_1107_164114_054A.avi -r -s -fps 6
 I have just found a regular phenomenon, the image registration work bad when the camera moving fast, and the moving object can be detected with  much error(such as stationary arrow marks on the ground can also be detected), otherwise ,when the car's speed is slow, the registration algorithm could  work well, the moving object can be detected no much error; 
But the when rectangle detected moving object, the bounding box is not stable, can not detect in each display frame.lost in some frames.and sometimes the border includes the whole moving object .sometimes just include part of the moving object.

**Comment by sthoduka** [comment]
Did you end up finding a different method to solve those issues?

**Comment by phenix1983** [comment]
No.I am just analysing. Have not resolved the problem.

**Comment by sthoduka** [comment]
ok cool. Please let me know if you resolve the problem :) I'd like to improve this if it's possible.
